# Generated by Django 6.0.3 on 2026-03-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('voice_type', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SongLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('LISTENER', 'Listener')], default='CREATOR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SHARED', 'Shared')], default='DRAFT', max_length=20)),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.generationparameters')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.songlibrary')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.user')),
            ],
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_link', to='music.song')),
            ],
        ),
        migrations.AddField(
            model_name='songlibrary',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='music.user'),
        ),
        migrations.CreateModel(
            name='SongGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='music.generationparameters')),
                ('result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_request', to='music.song')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='music.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='music.user')),
            ],
        ),
    ]
