# Generated by Django 6.0.3 on 2026-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songgenerationrequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
